version: "3.8"

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: shiply-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    restart: unless-stopped
    networks:
      - shiply-network

  shiply-db:
    image: postgres:13
    container_name: shiply-db
    environment:
      POSTGRES_DB: shiply
      POSTGRES_USER: shiply
      POSTGRES_PASSWORD: shiply
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shiply-network
    restart: unless-stopped

  shiply-api:
    build: .
    container_name: shiply-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://shiply:shiply@shiply-db:5432/shiply
      - PASS_SEC=shiply-secret-key-2025-very-secure-password-encryption
    ports:
      - "3000:3000"
    networks:
      - shiply-network
    depends_on:
      - shiply-db
      - nginx-proxy

volumes:
  postgres_data:

networks:
  shiply-network:
    driver: bridge
