version: "3.8"

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: shiply-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    restart: unless-stopped
    networks:
      - shiply-network

  shiply-api:
    image: node:18-alpine
    container_name: shiply-api
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - shiply-network
    depends_on:
      - nginx-proxy

networks:
  shiply-network:
    driver: bridge
